### ISSUE TITLE
The name tho

### ISSUE THREAD

**Issue by tuxxy** [nucypher/bytestringSplitter#3]
1. Why is it byte_S_tringSplitter? I think it's just bytestring.
2. Why not use something like bytesSplitter or byteSplitter. I like byteSplitter.
3. Let's get this up on pypi muy rapidamente!

**Comment by jMyles** [comment]
1.  Haha... right.  Right.
2. When it sounds like it splits bytes into bits.  
3. Umm, yeah, I guess it's time.

@KPrasch also doesn't like the name.

**Comment by jMyles** [comment]
bytestringMonster?

`monster = BytestringMonster(...)`
`monster.om_nom_nom(splittable)`

**Comment by KPrasch** [comment]
Nom Nom - Closable? I like the name after some time passed. Almost sounds like were chopping wood!
